### ISSUE TITLE
Basic example didn't work

### ISSUE THREAD

**Issue by BdT141** [sdementen/piecash2#8]
**Describe the bug**
I used the sample code from the repo's readme file and used it to open my gnucash book but I got the following error:

> Traceback (most recent call last):
>   File "E:\Python Projects\PieCashProjector\main.py", line 16, in <module>
>     main()
>   File "E:\Python Projects\PieCashProjector\main.py", line 5, in main
>     Session = open_book("test.gnucash")
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\Python Projects\PieCashProjector\.venv\Lib\site-packages\piecash2\core\book.py", line 21, in open_book
>     source.backup(dest)
> sqlite3.DatabaseError: file is not a database

**To Reproduce**
[test.txt](https://github.com/user-attachments/files/17234600/test.txt)
I've attached the empty gnucash file renamed to .txt so I could attach it.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11
 - Python: 3.11

**Comment by BdT141** [comment]
Nevermind, the file wasn't saved in sqlite format. Please remove this issue. thanks
